In [2]:
import numpy as np
import matplotlib
# matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import bernoulli
from scipy.stats import pareto
import networkx as nx
import matplotlib.pyplot as plt
import random
import scipy.io
import collections
import pickle
from mpl_toolkits.axes_grid1.inset_locator import (inset_axes,InsetPosition,mark_inset)
import copy
import itertools

In [3]:
from Methods import *

# Generating the Results
## To generate the results: set the parameters in the cell below and then run the remaining cells (in the HMM Framework and IID Framework sections).

In [4]:
# Parameters for numerical experiments

T_Vec = [60,90,120,150,180] #Calibration sequence lengths
T1 = 3 #Prediction length
PERF = 0 # 0: without exact P,B values, 1: with exact P,B values
Algo = 'Filter' #Filter or Smoother
ALPHA = 0.2 #Desired miscoverage level
NUM_ITER = 500 #Number of Monte-Carlo Iterations
b_vec = [0.3333,0.6,0.9] #Parameter of the Observation Probability Matrix (value of each diagonal element of B)
p0 = np.array([1/3, 1/3, 1/3]) #Distribution of Initial states

## HMM Framework

In [5]:
#Transition Probability Matrix
P = np.array([[0.1, 0.6, 0.3], [0.3, 0.1, 0.6], [0.6, 0.3, 0.1]]) #HMM Setting

In [ ]:
for b in b_vec:
    for T in T_Vec:
        if b == 0.3333:
            VERSION = 'V1'
        if b == 0.6:
            VERSION = 'V2'
        if b == 0.9:
            VERSION = 'V3'
            
        calX_LEN = np.shape(P)[1] #State space {0,1,2} cardinality    
            
        #Observation Probability Matrix
        B = np.array([[b, (1-b)/2, (1-b)/2], [(1-b)/2, b, (1-b)/2], [(1-b)/2, (1-b)/2, b]])            
        calY_LEN = np.shape(B)[1] #Observation space {0,1,2} cardinality
        
   
        Name = 'Outputs_of_'+ VERSION +'_' + Algo + '_Perf_' + str(PERF) + '_CPHMM_alpha_pt_2_T_' + str(T) + '_T1_' + str(T1) + '.pkl'
        with open(Name, "wb") as fp:   #Pickling
            pickle.dump([], fp)

        print(Name)

        with open(Name, 'rb') as f:
            Outputs_of_CPHMM = pickle.load(f)

        while len(Outputs_of_CPHMM)<NUM_ITER:    
            XY_full = sim_HMM(p0, P, B, (T+T1))

            X = XY_full[0][:-T1]
            Y = XY_full[1][:-T1]

            X_pred = XY_full[0][-T1:]
            Y_pred = XY_full[1][-T1:]


            print("")    
            print("*********BEGINNING A NEW ITERATION*********")   
            print(Name)
            print("Length:")
            print(len(Outputs_of_CPHMM))

            print("True State Sequence: ")    
            print(X_pred)
            print("")

            if Algo == 'Smoother':
                OP = CP_HMM_smoothing(X, Y, X_pred, Y_pred, ALPHA, calX_LEN, calY_LEN, perf = PERF)
            if Algo == 'Filter':
                OP = CP_HMM_filtering(X, Y, X_pred, Y_pred, ALPHA, calX_LEN, calY_LEN, perf = PERF)

            Outputs_of_CPHMM.append(OP)

            with open(Name, "wb") as fp:   #Pickling
                pickle.dump(Outputs_of_CPHMM, fp)   


            print("*********SUMMARY OF THE FINISHED ITERATION*********")
            print("True State Sequence: ")
            print(Outputs_of_CPHMM[-1][0])

            print("Output Set of Sequences: ")
            print(Outputs_of_CPHMM[-1][1])

            print("True State is in Prediction Set: ")
            print(Outputs_of_CPHMM[-1][0] in Outputs_of_CPHMM[-1][1])



Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
0
True State Sequence: 
[1 1 0]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(1, 1, 0)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 2, 0), (0, 2, 1), (0, 2, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 2, 0), (1, 2, 1), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
1
True State Sequence: 
[2 1 2]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 1, 2)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 2, 1), (1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 2, 0), (1, 2, 1), (1, 2, 2), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 0, 1)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 2), (1, 0, 2), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1), (2, 2, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
18
True State Sequence: 
[2 1 0]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 1, 0)
Output Set of Sequences: 
[(0, 0, 0), (0, 1, 0), (0, 2, 0), (0, 2, 2), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1), (1, 2, 0), (1, 2, 1), (1, 2, 2), (2, 0, 0), (2, 1, 0), (2, 2, 0), (2, 2, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
19
True State Sequence: 
[0 1 2]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(0, 1, 2)
Output Set of Sequences: 
[

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 0, 1)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 2), (0, 2, 0), (0, 2, 2), (1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 2, 0), (1, 2, 1), (1, 2, 2), (2, 0, 0), (2, 0, 2), (2, 2, 0), (2, 2, 2)]
True State is in Prediction Set: 
False

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
35
True State Sequence: 
[2 1 0]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 1, 0)
Output Set of Sequences: 
[(0, 0, 2), (0, 1, 2), (0, 2, 2), (1, 0, 2), (1, 1, 1), (1, 1, 2), (1, 2, 2), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1), (2, 2, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
36
True State Sequence: 
[1 2 0]

*********SUMMARY OF THE FINISHED ITERATION**

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 1, 2)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (1, 0, 0), (1, 1, 0), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1), (2, 2, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
53
True State Sequence: 
[0 2 0]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(0, 2, 0)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 2, 0), (0, 2, 1), (0, 2, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 2, 1), (2, 1, 0), (2, 1, 1), (2, 1, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
54
True State Sequence: 
[0 1 2]

*********SUMMARY OF THE FINISHED ITERATION***

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(0, 2, 0)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 2, 0), (0, 2, 1), (0, 2, 2), (1, 1, 0), (1, 1, 2), (1, 2, 0), (1, 2, 2), (2, 1, 0), (2, 1, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
71
True State Sequence: 
[2 0 1]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 0, 1)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 1), (0, 2, 2), (1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 1, 1), (1, 2, 2), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1), (2, 2, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
72
True State Sequence: 
[0 1 0]

*********SUMMARY OF THE FINISHED I

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 0, 1)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 2, 0), (0, 2, 1), (0, 2, 2), (1, 0, 0), (1, 2, 1), (1, 2, 2), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1), (2, 2, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
89
True State Sequence: 
[2 0 1]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(2, 0, 1)
Output Set of Sequences: 
[(0, 0, 0), (1, 0, 0), (1, 0, 2), (1, 1, 0), (1, 1, 2), (1, 2, 0), (1, 2, 2), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 2), (2, 2, 0), (2, 2, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
90
True State Sequence: 
[2 0 1]

*********SUMMARY OF THE

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(0, 1, 2)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 2, 0), (0, 2, 1), (0, 2, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2)]
True State is in Prediction Set: 
True

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
107
True State Sequence: 
[1 1 0]

*********SUMMARY OF THE FINISHED ITERATION*********
True State Sequence: 
(1, 1, 0)
Output Set of Sequences: 
[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (1, 0, 1), (1, 0, 2), (1, 1, 1), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1), (2, 2, 2)]
True State is in Prediction Set: 
False

*********BEGINNING A NEW ITERATION*********
Outputs_of_V1_Filter_Perf_0_CPHMM_alpha_pt_2_T_60_T1_3.pkl
Length:
108
True State Sequence: 
[1 0 1]



## IID Framework

In [ ]:
#Transition Probability Matrix
P = np.array([[1/3, 1/3, 1/3], [1/3, 1/3, 1/3], [1/3, 1/3, 1/3]]) #IID Setting

In [ ]:
for b in b_vec:
    for T in T_Vec:
        if b ==0.3333:
            VERSION = 'V1'
        if b == 0.6:
            VERSION = 'V2'
        if b == 0.9:
            VERSION = 'V3'
            
        calX_LEN = np.shape(P)[1] #State space {0,1,2} cardinality    
            
        #Observation Probability Matrix
        B = np.array([[b, (1-b)/2, (1-b)/2], [(1-b)/2, b, (1-b)/2], [(1-b)/2, (1-b)/2, b]])            
        calY_LEN = np.shape(B)[1] #Observation space {0,1,2} cardinality
        
        
        Name = 'Outputs_of_IID_'+ VERSION +'_' + Algo + '_Perf_' + str(PERF) + '_CPHMM_alpha_pt_2_T_' + str(T) + '_T1_' + str(T1) + '.pkl'
        with open(Name, "wb") as fp:   #Pickling
            pickle.dump([], fp)

        print(Name)

        with open(Name, 'rb') as f:
            Outputs_of_CPHMM = pickle.load(f)

        while len(Outputs_of_CPHMM)<NUM_ITER:    
            XY_full = sim_HMM(p0, P, B, (T+T1))

            X = XY_full[0][:-T1]
            Y = XY_full[1][:-T1]

            X_pred = XY_full[0][-T1:]
            Y_pred = XY_full[1][-T1:]


            print("")    
            print("*********BEGINNING A NEW ITERATION*********") 
            print(Name)
            print("Length:")
            print(len(Outputs_of_CPHMM))

            print("True State Sequence: ")    
            print(X_pred)
            print("")

            if Algo == 'Smoother':
                OP = CP_HMM_smoothing(X, Y, X_pred, Y_pred, ALPHA, calX_LEN, calY_LEN, perf = PERF)
            if Algo == 'Filter':
                OP = CP_HMM_filtering(X, Y, X_pred, Y_pred, ALPHA, calX_LEN, calY_LEN, perf = PERF)

            Outputs_of_CPHMM.append(OP)

            with open(Name, "wb") as fp:   #Pickling
                pickle.dump(Outputs_of_CPHMM, fp)   


            print("*********SUMMARY OF THE FINISHED ITERATION*********")
            print("True State Sequence: ")
            print(Outputs_of_CPHMM[-1][0])

            print("Output Set of Sequences: ")
            print(Outputs_of_CPHMM[-1][1])

            print("True State is in Prediction Set: ")
            print(Outputs_of_CPHMM[-1][0] in Outputs_of_CPHMM[-1][1])



# Visualizing Results
## To visualize the results: set the $T_1$ in the cell below and then run the remaining cels.

In [ ]:
T1 = 3 #Prediction length

In [ ]:
plt.rcParams["mathtext.fontset"]
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8.02, 4.))

COLS = ['g','m', 'b', 'y']
MARKERS = ['s', 'o', '^']
LINESTYLES = ['--', '-.', ':']
BASE_MARKER_SIZE = 6; MARKER_STEP_SIZE = 0
MARKERSIZE = [BASE_MARKER_SIZE,BASE_MARKER_SIZE-MARKER_STEP_SIZE,BASE_MARKER_SIZE-2*MARKER_STEP_SIZE]
B_VEC = ['1/3','0.6','0.9']
margin_for_lines = 0.03 

calX_LEN = 3 #Size of the state space
STATE_SPACE_CARD = calX_LEN**T1 #Size of the space of candidate sequences

for V in [0,1,2]:
    Average_Prediction_Set_Size_Vec = list([])
    TrueFraction_Vec = list([])
    for T in T_Vec:        
        Name = 'Outputs_of_V' + str(V+1) + '_'+ Algo + '_Perf_' + str(PERF) + '_CPHMM_alpha_pt_2_T_' + str(T) + '_T1_' + str(T1) + '.pkl'
        with open(Name, 'rb') as f:
            Outputs_of_CPHMM = pickle.load(f) 

        ITER = 0
        Prediction_Set_Size = 0
        TrueCount = 0    
        while ITER < len(Outputs_of_CPHMM):
            if Outputs_of_CPHMM[ITER][0] in Outputs_of_CPHMM[ITER][1]:
                TrueCount = TrueCount + 1
            Prediction_Set_Size = Prediction_Set_Size + len(Outputs_of_CPHMM[ITER][1]) 
            ITER += 1    

        TrueFraction_Vec = [*TrueFraction_Vec, TrueCount/len(Outputs_of_CPHMM)]
        Average_Prediction_Set_Size_Vec = [*Average_Prediction_Set_Size_Vec, (Prediction_Set_Size/len(Outputs_of_CPHMM))/STATE_SPACE_CARD]

    
    ax1.plot(T_Vec, list(np.around(TrueFraction_Vec, 2)), color = COLS[0] , linestyle = LINESTYLES[V], marker = MARKERS[V], markerfacecolor='none', markersize = MARKERSIZE[V], label=r'Empirical Coverage for $b = $'+B_VEC[V])
    ax1.plot(T_Vec, Average_Prediction_Set_Size_Vec, color = COLS[1] , linestyle = LINESTYLES[V], marker = MARKERS[V], markerfacecolor='none', markersize = MARKERSIZE[V],label=r'$\mathrm{\frac{\mathbb{E}\{|\mathcal{C}_{0.8}|\}}{|\mathcal{X}^{T_1}|}}$ for $b=$'+B_VEC[V])    
   
   
    
for V in [0,1,2]:
    Average_Prediction_Set_Size_Vec = list([])
    TrueFraction_Vec = list([])
    for T in T_Vec:     
        Name = 'Outputs_of_IID_V' + str(V+1) + '_'+ Algo + '_Perf_' + str(PERF) + '_CPHMM_alpha_pt_2_T_' + str(T) + '_T1_' + str(T1) + '.pkl'
        with open(Name, 'rb') as f:
            Outputs_of_CPHMM = pickle.load(f) 

        ITER = 0
        Prediction_Set_Size = 0
        TrueCount = 0    
        while ITER < len(Outputs_of_CPHMM):
            if Outputs_of_CPHMM[ITER][0] in Outputs_of_CPHMM[ITER][1]:
                TrueCount = TrueCount + 1
            Prediction_Set_Size = Prediction_Set_Size + len(Outputs_of_CPHMM[ITER][1]) 
            ITER += 1    

        TrueFraction_Vec = [*TrueFraction_Vec, TrueCount/len(Outputs_of_CPHMM)]
        Average_Prediction_Set_Size_Vec = [*Average_Prediction_Set_Size_Vec, (Prediction_Set_Size/len(Outputs_of_CPHMM))/STATE_SPACE_CARD]

    
    ax2.plot(T_Vec, list(np.around(TrueFraction_Vec, 2)), color = COLS[0] , linestyle = LINESTYLES[V], marker = MARKERS[V], markerfacecolor='none', markersize = MARKERSIZE[V], label=r'Empirical coverage for $b = $'+B_VEC[V])    
    ax2.plot(T_Vec, Average_Prediction_Set_Size_Vec, color = COLS[1] , linestyle = LINESTYLES[V], marker = MARKERS[V], markerfacecolor='none', markersize = MARKERSIZE[V],label=r'$\mathbb{E}\{|\mathcal{C}_{0.8}|\}$ (scaled by $|\mathcal{X}^{T_1}|$) for $b=$'+B_VEC[V])    
   

ax1.grid()
ax1.set_xlabel(r'Calibration sequence length $T$', fontsize = 11.5)
ax1.set_ylabel('Empirical coverage & \n scaled prediction set size', fontsize = 11.5)
ax1.set_xticks(T_Vec)
ax1.tick_params(axis='both', which='minor', labelsize=12)

    
ax2.grid()
ax2.set_xlabel(r'Calibration sequence length $T$', fontsize = 11.5)
ax2.set_xticks(T_Vec)
ax2.tick_params(axis='both', which='minor', labelsize=11.5)

ax2.axhline(y=0.8, xmin=0, xmax=3, c='r', linestyle = '-', linewidth=2, zorder=0)
ax2.axhline(y=0.8 - margin_for_lines, xmin=0, xmax=3, c='r', linestyle = ':', linewidth=1, zorder=0)
ax2.axhline(y=0.8 + margin_for_lines, xmin=0, xmax=3, c='r', linestyle = ':', linewidth=1, zorder=0)
    
ax1.axhline(y=0.8, xmin=0, xmax=3, c='r', linestyle = '-', linewidth=2, zorder=0, label=r'Desired coverage $1-\alpha = 0.8$')
ax1.axhline(y=0.8 - margin_for_lines, xmin=0, xmax=3, c='r', linestyle = ':', linewidth=1, zorder=0, label=r'$\pm$' + str(margin_for_lines) + r' margins of $1-\alpha$')
ax1.axhline(y=0.8 + margin_for_lines, xmin=0, xmax=3, c='r', linestyle = ':', linewidth=1, zorder=0)

ax1.legend(loc='upper center', bbox_to_anchor=(1.08, 1.6), fontsize = 11.75, edgecolor = 'inherit', ncol = 2)

ax1.set_title('HMM Setting')
ax2.set_title('IID Setting')

ax1.set_ylim(0.1,1)
ax2.set_ylim(0.1,1)

fig.text(0.275, -0.07, '(a)', fontsize = 15)
fig.text(0.7, -0.07, '(b)', fontsize = 15)

plt.savefig('CP_Filter_All_Numerical_Results_T1_'+str(T1)+'.pdf', bbox_inches='tight')                                      
